global:
  raw_data_dir: "/mnt/data/raw"
  processed_data_dir: "/mnt/data/processed"

model:
  # model name. see factory.py for options
  model_name: "random_forest"
  # model params
  model_params: {}
  # dir to save model weights
  model_dir: "/mnt/model_cache"
  # name to save model weights to
  filename: "demo_model"

train:


evaluate:
  # Flag to retrain the model or not. If False, then the cached model from model->model_dir will be used as model.
  retrain: True
  # MLFlow experiment name
  experiment_name: "test"
